// Browser com HTML/módulo reais e API simulada: nenhum servidor Harness, conta ou LLM real.
import {traduzPagina,carregaCatalogos} from './web/site-i18n.mjs';
import {marcaNaPagina} from './web/marca.mjs';import {leitorDoApp} from './web/plugins.mjs';
import {chromium} from 'playwright-core';import {readFileSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';import {resolve,extname} from 'node:path';import assert from 'node:assert/strict';
const root=resolve('web/public'),source=leitorDoApp([],root+'/index.html')(root+'/index.html'),html=source.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');
// Núcleo sem plugin nem marca: os encaixes somem e o nome é o padrão.
const catalogos=carregaCatalogos(resolve('web/site-textos'));
const out=process.env.ONBOARDING_SCREENSHOTS||'/tmp/brambs-onboarding-browser';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});let checks=0;
const A='00000000-0000-4000-8000-000000000002';
const meBase={name:'Pessoa de teste',agents:[{id:A,name:'Meu assistente'}],connected:['gmail','calendar'],providers:[],whatsapp:{linked:true,number:'5511999999999'}};
const ready={registered:true,agentId:A,step:'wow',status:'done',mode:'connected',attemptId:'attempt-1',result:{welcome:'Seu resultado personalizado está salvo. Você tem duas prioridades para organizar.',suggestions:['Organizar as prioridades de hoje'],notes:[]},viewed:false,completed:false};
async function fixture({me=structuredClone(meBase),state=structuredClone(ready),local=null,failStatus=0,idleStatus=0,failPost=false,postDelay=0,width=390,language='pt-BR',touchFails=false,feedbackFails=false,meFailures=0}={}){
 const page=await browser.newPage({viewport:{width,height:844}}),calls=[],errors=[];page.on('pageerror',e=>errors.push(e.message));let current=state,failures=failStatus,idles=idleStatus;
 await page.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());
  if(url.pathname.startsWith('/api/')){let body={};try{body=req.postDataJSON()||{}}catch{}calls.push({path:url.pathname,query:url.search,body});
   const answer=(d,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(d)});
   if(url.pathname==='/api/onboard/feedback'){if(feedbackFails)return answer({error:'synthetic feedback failure'},503);assert.equal(body.attemptId,current.attemptId);assert(current.viewed);current.feedback=body.choice;return answer(current)}
   if(url.pathname==='/api/onboard/touch')return answer({ok:!touchFails},touchFails?503:200);
   if(url.pathname.endsWith('/start')&&url.pathname.startsWith('/api/connect/'))return route.abort('aborted');
   if(url.pathname==='/api/me'){if(meFailures-->0)return answer({error:'Falha temporária ao entrar.'},503);return answer(me);}
   if(url.pathname==='/api/agent'){me.agents=[{id:A,name:body.name}];return answer(me.agents[0])}
   if(url.pathname==='/api/onboard/status'){if(failures-->0)return route.abort('failed');if(idles-->0)return answer({registered:true,agentId:A,status:'idle'});return answer(current||{status:'idle',registered:false})}
   if(url.pathname==='/api/onboard/progress'){
    current ||= {registered:true,agentId:A,status:'idle',step:'connect'};
    if(body.event==='started'){}else if(body.event==='connections_skipped')current.step='wow';else if(body.event.startsWith('connections_'))current.step='whatsapp';else if(body.event.startsWith('whatsapp_'))current.step=current.viewed?'done':'wow';
    if(body.event.endsWith('_viewed')){assert.equal(body.attemptId,current.attemptId);current.viewed=true}
    if(body.event==='suggestion_selected'){current.selectedSuggestion=body.selection;current.refinementSelected=false;current.step='done'}
    if(body.event==='refinement_selected'){current.refinementSelected=true;current.selectedSuggestion=null;current.step='done'}
    if(body.event==='wow_skipped')current.skipped=true;
    if(body.event==='completed'){if(!current.viewed&&!current.skipped)return answer({error:'Etapa incompleta'},409);current.completed=true;current.step='done'}
    return answer(current);
   }
   if(url.pathname==='/api/onboard'){if(postDelay)await new Promise(r=>setTimeout(r,postDelay));if(failPost)return answer({error:'Falha ao iniciar; tente novamente.'},503);current={...structuredClone(ready),mode:body.mode||'connected'};if(body.mode==='starter'){current.result={welcome:'Aqui está um plano feito só com o contexto que você informou: comece pela entrega urgente e reserve um bloco para a reunião.',suggestions:[],notes:[]}}return answer(current)}
   if(url.pathname==='/api/connect/whatsapp'){me.whatsapp.linked=true;return answer({number:me.whatsapp.number})}
   return answer({});
  }
  const p=resolve(root,'.'+url.pathname);if(p.startsWith(root+'/')&&existsSync(p)&&url.pathname!='/inicio'){const type={'.mjs':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2'}[extname(p)]||'application/octet-stream';return route.fulfill({status:200,contentType:type,body:readFileSync(p)})}
  return route.fulfill({status:200,contentType:'text/html',body:marcaNaPagina(traduzPagina(html,language,catalogos))});
 });
 await page.goto('http://onboarding.test/inicio');await page.evaluate(({local})=>{document.body.classList.remove('booting');if(local)localStorage.setItem('mtr_wiz',JSON.stringify(local))}, {local});
 const mount=()=>page.evaluate(async()=>{document.body.classList.remove('booting');const {mountWizard}=await import('/onboarding.mjs');window.wizard=mountWizard({generic:{id:'geral',name:'Brambs',goal:'Assistente completo',instructions:'Ajude a pessoa',connect:['gmail','calendar','docs','drive'],tasks:[]},config:()=>({microsoft:true}),showApp:on=>document.getElementById('app').classList.toggle('hidden',!on),enterHome:(me,task)=>{window.entered={me,task};document.getElementById('app').classList.remove('hidden')}})});
 await mount();
 const boot=(just=false,oauth=null)=>page.evaluate(({me,just,oauth})=>window.wizard.boot(me,just,oauth),{me,just,oauth});
 const finish=async(name)=>{assert.deepEqual(errors,[],name+' console');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' overflow');await page.screenshot({path:out+'/'+name+'.png',fullPage:true});checks++;await page.close()};return {page,boot,finish,calls,reload:async()=>{await page.reload();await mount();},getState:()=>current,setFail:n=>{failures=n},setIdle:n=>{idles=n}};
}
try{
 for(const language of ['pt-BR','en','es']){const f=await fixture({language});await f.boot();await f.page.locator('#wowUseful').waitFor({state:'visible'});await f.page.click('#wowUseful');await f.page.waitForFunction(()=>document.querySelector('#wowUseful').getAttribute('aria-pressed')==='true');assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);await f.page.click('#wowNeedsWork');await f.page.waitForFunction(()=>document.querySelector('#wowNeedsWork').getAttribute('aria-pressed')==='true');await f.page.click('#wowRefine');await f.reload();await f.boot();await f.page.locator('#wizDoneBtn').waitFor({state:'visible'});await f.page.click('#wizDoneBtn');await f.page.waitForFunction(()=>!!window.entered);assert.match((await f.page.evaluate(()=>window.entered)).task,/Seu resultado personalizado/);assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);await f.finish('feedback-refinement-'+language)}
 {const f=await fixture();await f.boot();await f.page.click('#wowSugs button');await f.reload();await f.boot();await f.page.click('#wizDoneBtn');await f.page.waitForFunction(()=>!!window.entered);assert.equal((await f.page.evaluate(()=>window.entered)).task,'Organizar as prioridades de hoje');await f.finish('selection-survives-reload')}
 {const f=await fixture({meFailures:1});await f.boot();await f.page.click('#wowSugs button');await f.page.click('#wizDoneBtn');await f.page.locator('#wizDoneErr').waitFor({state:'visible'});assert(!f.getState().completed);await f.reload();await f.boot();await f.page.click('#wizDoneBtn');await f.page.waitForFunction(()=>!!window.entered);assert.equal((await f.page.evaluate(()=>window.entered)).task,'Organizar as prioridades de hoje');await f.finish('entry-failure-keeps-selection')}
 {const f=await fixture({feedbackFails:true});await f.boot();await f.page.click('#wowUseful');await f.page.getByText('Não consegui salvar sua avaliação. Você pode continuar e tentar novamente depois.').waitFor();assert(await f.page.locator('#wowBtn').isVisible());await f.page.click('#wowBtn');await f.page.click('#wizDoneBtn');await f.page.waitForFunction(()=>!!window.entered);assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);await f.finish('feedback-failure-does-not-block')}
 for(const width of [390,768,1280]){const f=await fixture({width});assert.equal(await f.boot(),true);await f.page.locator('#wowBtn').waitFor({state:'visible'});assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);assert(f.calls.some(x=>x.body.event==='wow_viewed'));await f.finish('resume-ready-'+width)}
 {const f=await fixture({local:null});await f.boot();await f.page.click('#wowSugs button');await f.page.click('#wizDoneBtn');await f.page.waitForFunction(()=>!!window.entered);assert.equal((await f.page.evaluate(()=>window.entered)).task,'Organizar as prioridades de hoje');assert(f.getState().completed);await f.finish('completed-after-selection')}
 {const f=await fixture({state:{...structuredClone(ready),step:'whatsapp'},me:{...structuredClone(meBase),whatsapp:{linked:false}}});await f.boot();await f.page.locator('#wowBtn').waitFor({state:'visible'});assert(f.calls.some(x=>x.body.event==='wow_viewed'));assert(!await f.page.locator('#wizWaSkip').isVisible());await f.page.click('#wowBtn');await f.page.locator('#wizWaSkip').waitFor({state:'visible'});await f.page.click('#wizWaSkip');await f.page.locator('#wizDoneBtn').waitFor({state:'visible'});await f.finish('result-before-whatsapp')}
 {const f=await fixture({me:{...structuredClone(meBase),connected:[],providers:['microsoft']},state:{registered:true,agentId:A,step:'wow',status:'idle'}});await f.boot();assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,1);await f.page.locator('#wowBtn').waitFor({state:'visible'});await f.finish('microsoft-resume')}
 {const f=await fixture({state:{registered:true,agentId:A,step:'wow',status:'error',errorCode:'interrupted'}});await f.boot();await f.page.locator('#wowRetry').waitFor({state:'visible'});assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);await f.page.click('#wowRetry');await f.page.locator('#wowBtn').waitFor({state:'visible'});assert.equal(f.calls.find(x=>x.path==='/api/onboard').body.retry,true);await f.finish('interrupted-retry')}
 {const f=await fixture({state:{registered:true,agentId:A,step:'wow',status:'idle'},failPost:true});await f.boot();await f.page.locator('#wowRetry').waitFor({state:'visible'});assert.equal(await f.page.locator('#wizStep-done').isVisible(),false);assert(!f.calls.some(x=>x.body.event==='completed'));await f.finish('post-failure-not-success')}
 {const f=await fixture({state:{registered:true,agentId:A,step:'wow',status:'idle'},postDelay:250,idleStatus:2,local:{agentId:A,agentName:'Meu assistente',step:'wow'}});await f.boot();await f.page.locator('#wowBtn').waitFor({state:'visible'});assert(f.calls.some(x=>x.body.event==='wow_viewed'));assert(!f.calls.some(x=>x.body.event==='completed'));await f.finish('idle-not-success')}
 {const f=await fixture({me:{...structuredClone(meBase),connected:[],providers:[],whatsapp:null},state:{registered:true,agentId:A,step:'wow',status:'idle'}});await f.boot();await f.page.locator('#wowStarter').waitFor({state:'visible'});await f.page.screenshot({path:out+'/starter-form-mobile.png',fullPage:true});assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);await f.page.fill('#wowContext','Tenho uma entrega amanhã e duas reuniões; preciso priorizar o trabalho.');await f.page.click('#wowStarterBtn');await f.page.locator('#wowBtn').waitFor({state:'visible'});const start=f.calls.find(x=>x.path==='/api/onboard');assert.equal(start.body.mode,'starter');assert.equal(start.body.task,'plan');assert(f.calls.some(x=>x.body.event==='starter_viewed'));assert(!f.calls.some(x=>x.body.event==='wow_viewed'));await f.finish('starter-no-connector')}
 {const f=await fixture({me:{...structuredClone(meBase),connected:[],whatsapp:null},state:{registered:true,agentId:A,step:'wow',status:'idle'}});await f.boot();await f.page.click('#wowSkip');await f.page.click('#wizDoneBtn');await f.page.waitForFunction(()=>!!window.entered);assert(!f.calls.some(x=>x.path==='/api/onboard'));assert(!f.calls.some(x=>x.body.event==='wow_viewed'));assert(f.calls.some(x=>x.body.event==='wow_skipped'));await f.finish('explicit-skip')}
 {const f=await fixture({state:null});assert.equal(await f.boot(),false);assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);await f.finish('existing-user-not-reonboarded')}
 {const f=await fixture({state:{registered:true,agentId:A,step:'wow',status:'running'}});const boot=f.boot();await f.page.locator('#wowLater').waitFor({state:'visible'});await f.page.click('#wowLater');await f.page.waitForFunction(()=>!!window.entered);await boot;assert(!f.getState().completed);assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);await f.finish('continue-later-running')}
 {const f=await fixture({failStatus:1,state:structuredClone(ready),local:null});assert.equal(await f.boot(),true);await f.page.locator('#wowRetry').waitFor({state:'visible'});assert.equal(await f.page.locator('#wizStep-done').isVisible(),false);await f.page.click('#wowRetry');await f.page.locator('#wowBtn').waitFor({state:'visible'});assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);await f.finish('boot-network-retry-no-local')}
 {const f=await fixture({me:{name:'Nova pessoa',agents:[],connected:[],providers:[],whatsapp:null},state:null});await f.boot();await f.page.fill('#wizAgentName','Meu primeiro assistente');await f.page.click('#wizTypeNext');await f.page.click('#wizConnSkip');await f.page.locator('#wowStarter').waitFor({state:'visible'});assert(f.calls.some(x=>x.body.event==='started'));assert(f.calls.some(x=>x.body.event==='connections_skipped'));assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);await f.finish('new-signup-no-connector')}
 {const f=await fixture({state:null,local:{agentId:A,agentName:'Meu assistente',step:'connect'},me:{...structuredClone(meBase),whatsapp:{linked:false}}});await f.boot();await f.page.locator('#wowBtn').waitFor({state:'visible'});assert(f.calls.some(x=>x.body.event==='connections_connected'));assert(f.calls.some(x=>x.body.event==='wow_viewed'));assert(!await f.page.locator('#wizWaSkip').isVisible());await f.finish('legacy-first-result-before-whatsapp')}
 for(const [language,heading] of [['en','A first look at your context'],['es','Un primer vistazo a tu contexto']]){const f=await fixture({language});await f.boot();assert.equal(await f.page.locator('#wowTitle').innerText(),heading);await f.finish('language-'+language)}

 for(const width of [390,768,1280]){
  const f=await fixture({width,state:null,me:{name:'Nova pessoa',agents:[],connected:[],providers:[],whatsapp:{linked:false}}});
  // Security disclosure is present before login too, no invented seals.
  assert.doesNotMatch(await f.page.locator('#authTrust').innerText(),/CASA/);await f.page.locator('#authTrust summary').click();assert.match(await f.page.locator('#authTrust').innerText(),/Entrar com o Google identifica sua conta/);await f.page.screenshot({path:out+'/signup-trust-'+width+'.png',fullPage:true});
  await f.boot();await f.page.fill('#wizAgentName','Meu assistente');await f.page.click('#wizTypeNext');await f.page.locator('#wizTrust').scrollIntoViewIfNeeded();
  await f.page.waitForFunction(()=>document.querySelector('#wizStep-connect').classList.contains('hidden')===false);
  const back=await f.page.locator('#wizConnBack').boundingBox(),skip=await f.page.locator('#wizConnSkip').boundingBox();
  assert.equal(await f.page.locator('#wizConnSkip').innerText(),'Continuar sem conectar');assert(back&&skip);assert(Math.abs(back.y-skip.y)<2,'footer links must share a row');assert(skip.x>back.x);assert.equal(await f.page.locator('.connect-actions #wizConnSkip').count(),0);
  await f.page.screenshot({path:out+'/connection-default-'+width+'.png',fullPage:true});
  await f.page.locator('#wizTrustDetails summary').click();await f.page.waitForTimeout(100);
  assert(f.calls.some(x=>x.path==='/api/onboard/touch'&&x.body.event==='security_viewed'));assert(f.calls.some(x=>x.body.event==='security_details_opened'));
  assert(!await f.page.locator('#wizStep-connect').getByText('Acesso só de leitura por enquanto.',{exact:false}).count());
  await f.page.screenshot({path:out+'/connection-trust-'+width+'.png',fullPage:true});await f.page.locator('#wizConnBtn').scrollIntoViewIfNeeded();await f.page.screenshot({path:out+'/connection-actions-'+width+'.png',fullPage:true});
  await f.page.click('#wizConnSkip');await f.page.locator('#wowStarter').waitFor({state:'visible'});
  assert.equal(await f.page.locator('#wizStep-whatsapp').isVisible(),false);assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);assert(f.calls.some(x=>x.body.event==='starter_offered'));
  await f.finish('trust-skip-direct-'+width);
 }
 for(const [provider,outcome,event] of [['google','cancelled','connection_cancelled'],['microsoft','cancelled','connection_cancelled'],['google','failed','connection_failed'],['microsoft','failed','connection_failed']]){
  const f=await fixture({state:{registered:true,agentId:A,step:'connect',status:'idle'},me:{...structuredClone(meBase),connected:[],providers:[]}});await f.boot(false,{provider,outcome});
  assert(await f.page.locator('#wizConnErr').isVisible());assert.match(await f.page.locator('#wizConnErr').innerText(),outcome==='cancelled'?/cancelou/:/não foi concluída/);assert(f.calls.some(x=>x.body.event===event&&x.body.provider===provider));assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);await f.finish(provider+'-'+outcome);
 }
 {const f=await fixture({state:{registered:true,agentId:A,step:'connect',status:'idle'},me:{...structuredClone(meBase),connected:[],providers:[]}});await f.boot(true);assert(await f.page.locator('#wizConnErr').isVisible());assert(f.calls.some(x=>x.body.event==='connection_returned_unconnected'));assert.equal(f.calls.filter(x=>x.path==='/api/onboard').length,0);await f.finish('callback-without-permissions')}
 {const f=await fixture({touchFails:true,state:null,me:{name:'Nova pessoa',agents:[],connected:[],providers:[],whatsapp:{linked:false}}});await f.boot();await f.page.fill('#wizAgentName','Teste');await f.page.click('#wizTypeNext');await f.page.click('#wizConnSkip');await f.page.locator('#wowStarter').waitFor({state:'visible'});await f.finish('metrics-outage-does-not-block-task')}
 for(const [language,label] of [['en','Continue without connecting'],['es','Continuar sin conectar']]){const f=await fixture({language,state:{registered:true,agentId:A,step:'connect',status:'idle'},me:{...structuredClone(meBase),connected:[],providers:[]}});await f.boot();assert.equal(await f.page.locator('#wizConnSkip').innerText(),label);await f.page.locator('#wizTrustDetails summary').click();assert(!/Essa avaliação/.test(await f.page.locator('#wizTrust').innerText()));await f.finish('trust-language-'+language)}
 for(const provider of ['google','microsoft'])for(const email of [false,true]){
  const f=await fixture({state:{registered:true,agentId:A,step:'connect',status:'idle'},me:{...structuredClone(meBase),connected:[],providers:[]}});await f.boot();
  assert.equal(await f.page.locator('#wizConnProviders').isVisible(),false);assert.doesNotMatch(await f.page.locator('#wizStep-connect').innerText(),/CASA|SOC 2|Drive|Gmail/);
  await f.page.click('#wizConnBtn');assert.equal(await f.page.locator('#wizConnProviders').isVisible(),true);assert.equal(await f.page.locator('#wizConnEmail').isChecked(),false);
  if(email)await f.page.check('#wizConnEmail');await f.page.screenshot({path:out+'/provider-choice-'+provider+'-'+email+'.png',fullPage:true});
  await f.page.click(provider==='google'?'#wizConnGoogle':'#wizConnMsRow');await f.page.waitForTimeout(100);
  const call=f.calls.find(c=>c.path==='/api/connect/'+provider+'/start');assert(call);assert.equal(new URLSearchParams(call.query).get('services'),email?'calendar,gmail':'calendar');assert(f.calls.some(c=>c.body.event==='connection_started'&&c.body.provider===provider));await f.finish('scope-'+provider+'-'+email);
 }
 {const f=await fixture({state:{registered:true,agentId:A,step:'connect',status:'idle'},me:{...structuredClone(meBase),connected:[],providers:['microsoft'],microsoftServices:[]}});await f.boot(true);assert(await f.page.locator('#wizConnErr').isVisible());assert(!f.calls.some(c=>c.path==='/api/onboard'));await f.finish('microsoft-identity-only-not-context')}
 {const f=await fixture({state:{registered:true,agentId:A,step:'wow',status:'idle'},me:{...structuredClone(meBase),connected:['calendar'],providers:[],whatsapp:null}});await f.boot(true);await f.page.locator('#wowBtn').waitFor({state:'visible'});assert(f.calls.some(c=>c.body.event==='wow_viewed'));await f.finish('calendar-only-result')}
 {const f=await fixture({state:{registered:true,agentId:A,step:'connect',status:'idle'},me:{...structuredClone(meBase),connected:[],providers:[]}});await f.boot();await f.page.focus('#wizConnBtn');await f.page.keyboard.press('Enter');assert.equal(await f.page.locator('#wizConnBtn').getAttribute('aria-expanded'),'true');assert(await f.page.locator('#wizConnGoogle').evaluate(el=>el===document.activeElement));await f.page.focus('#wizConnEmail');await f.page.keyboard.press('Space');assert(await f.page.locator('#wizConnEmail').isChecked());await f.finish('keyboard-calendar-choice')}
 writeFileSync(out+'/result.json',JSON.stringify({scenarios:checks,status:'passed',productionRequests:0},null,2));console.log(`PASS: ${checks} browser scenarios; desktop/tablet/mobile; no production requests.`);
}finally{await browser.close()}
