import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';
import {createOnboardingStore,publicState,starterPrompt,resultInput,type Pool,type Db} from './store.mjs';
const U='00000000-0000-4000-8000-000000000001',A='00000000-0000-4000-8000-000000000002',V='00000000-0000-4000-8000-000000000003',B='00000000-0000-4000-8000-000000000004';
const R={welcome:'Olá! Este é um resultado útil de teste.',suggestions:['Organizar prioridades'],notes:[]};
async function fixture(){const db=new PGlite();await db.exec(`CREATE SCHEMA mtr_harness;CREATE TABLE mtr_harness.users(id uuid PRIMARY KEY);CREATE TABLE mtr_harness.agents(id uuid PRIMARY KEY,user_id uuid,archived_at timestamptz);INSERT INTO mtr_harness.users VALUES('${U}'),('${V}');INSERT INTO mtr_harness.agents VALUES('${A}','${U}',NULL),('${B}','${V}',NULL);`);
 const query=async <T=Record<string,unknown>,>(s:string,a?:unknown[])=>{if(!a&&s.includes('CREATE TABLE')){await db.exec(s);return {rows:[] as T[]}}return db.query<T>(s,a)};
 let tail=Promise.resolve();const pool:Pool={query,async connect(){const previous=tail;let done!:()=>void;tail=new Promise<void>(r=>{done=r});await previous;return {query,release:done}}};const store=createOnboardingStore(pool,'10000000-0000-4000-8000-000000000001');await store.init();return {db,pool,store,close:()=>db.close()};}
test('state is opt-in, owned, immutable across retry of success and durable across new worker',async()=>{const f=await fixture();try{assert.equal(await f.store.get(U),null);assert.equal(await f.store.get(U,A),null);await assert.rejects(()=>f.store.progress(U,B,'started'),{status:404});await f.store.progress(U,A,'started');const q=await f.store.claim(U,A,'connected');assert(q.claimed);await f.store.finish(U,A,q.state.attempt_id!,R);const next=createOnboardingStore(f.pool);assert.equal((await next.get(U,A))?.status,'done');assert.equal((await next.claim(U,A,'connected',true)).claimed,false);assert.equal((await f.db.query('SELECT * FROM mtr_harness.onboarding_events')).rows.length,3)}finally{await f.close()}});
test('concurrent starts claim once; retries do not spend while running',async()=>{const f=await fixture();try{const q=await Promise.all([f.store.claim(U,A,'connected'),f.store.claim(U,A,'connected')]);assert.equal(q.filter(s=>s.claimed).length,1);assert.equal(q[0].state.attempt_id,q[1].state.attempt_id)}finally{await f.close()}});
test('restart becomes recoverable, requires retry, stale job cannot overwrite or fail replacement',async()=>{const f=await fixture();try{const old=await f.store.claim(U,A,'connected');const next=createOnboardingStore(f.pool,'20000000-0000-4000-8000-000000000001');assert.equal((await next.get(U,A))?.error_code,'interrupted');assert.equal((await next.claim(U,A,'connected')).claimed,false);const fresh=await next.claim(U,A,'connected',true);assert(fresh.claimed);assert.equal(await f.store.finish(U,A,old.state.attempt_id!,R),false);assert.equal(await f.store.fail(U,A,old.state.attempt_id!),false);assert.equal((await next.get(U,A))?.status,'running');assert(await next.finish(U,A,fresh.state.attempt_id!,R))}finally{await f.close()}});
test('viewed is distinct from ready; event acknowledgement is scoped to current attempt',async()=>{const f=await fixture();try{const q=await f.store.claim(U,A,'connected');await f.store.finish(U,A,q.state.attempt_id!,R);assert.equal((await f.store.get(U,A))?.viewed_at,null);await assert.rejects(()=>f.store.progress(U,A,'completed'),{status:409});await assert.rejects(()=>f.store.progress(U,A,'wow_viewed','wrong'),{status:409});await assert.rejects(()=>f.store.progress(V,A,'wow_viewed',q.state.attempt_id),{status:404});await f.store.progress(U,A,'wow_viewed',q.state.attempt_id);await f.store.progress(U,A,'wow_viewed',q.state.attempt_id);await f.store.progress(U,A,'completed');assert.equal(await f.store.get(U),null);assert.equal((await f.db.query<{n:number}>("SELECT count(*)::int n FROM mtr_harness.onboarding_events WHERE event='wow_viewed'")).rows[0].n,1)}finally{await f.close()}});
test('explicit skip is not a wow; privacy-minimal event shape, deletion cascades',async()=>{const f=await fixture();try{await f.store.progress(U,A,'started');await f.store.progress(U,A,'connections_skipped');await f.store.progress(U,A,'wow_skipped');await f.store.progress(U,A,'completed');const x=publicState(await f.store.get(U,A));assert.equal('viewed' in x&&x.viewed,false);assert.equal('completed' in x&&x.completed,true);const cols=(await f.db.query<{column_name:string}>("SELECT column_name FROM information_schema.columns WHERE table_name='onboarding_events'")).rows.map(x=>x.column_name);assert(!cols.includes('context')&&!cols.includes('result'));await f.db.query('DELETE FROM mtr_harness.agents WHERE id=$1',[A]);assert.equal((await f.db.query('SELECT * FROM mtr_harness.onboarding_events')).rows.length,0)}finally{await f.close()}});
test('starter has separate milestones and no connector is necessary',async()=>{const f=await fixture();try{const q=await f.store.claim(U,A,'starter');await f.store.finish(U,A,q.state.attempt_id!,{...R,suggestions:[]});await assert.rejects(()=>f.store.progress(U,A,'wow_viewed',q.state.attempt_id),{status:400});await f.store.progress(U,A,'starter_viewed',q.state.attempt_id);const events=(await f.db.query<{event:string}>('SELECT event FROM mtr_harness.onboarding_events')).rows.map(x=>x.event);assert(events.includes('starter_requested')&&events.includes('starter_ready')&&events.includes('starter_viewed'));assert(!events.includes('wow_viewed'))}finally{await f.close()}});
test('malformed result, unknown event, invalid identifiers and starter limits fail closed',async()=>{const f=await fixture();try{await assert.rejects(()=>f.store.progress(U,A,'inject'),{status:400});await assert.rejects(()=>f.store.get(U,"' OR 1=1"),{status:400});assert.throws(()=>resultInput({...R,suggestions:[]},'connected'),{status:422});for(const bad of ['constructor','__proto__','toString'])assert.throws(()=>starterPrompt(bad,'Contexto de teste','pt'),{status:400});assert.throws(()=>starterPrompt('send','Write an email','pt'),{status:400});assert.throws(()=>starterPrompt('plan','x','pt'),{status:400});assert.throws(()=>starterPrompt('plan','x'.repeat(2001),'pt'),{status:400});assert.match(starterPrompt('draft','Responder convite com educação','pt'),/without sending it/);const q=await f.store.claim(U,A,'connected');await assert.rejects(()=>f.store.finish(U,A,q.state.attempt_id!,{...R,welcome:''}),{status:422});assert.equal((await f.store.get(U,A))?.status,'running');await f.store.fail(U,A,q.state.attempt_id!);assert.equal((await f.store.get(U,A))?.status,'error')}finally{await f.close()}});
test('legacy status retains welcome and status, excludes private database fields',async()=>{const f=await fixture();try{const q=await f.store.claim(U,A,'connected');await f.store.finish(U,A,q.state.attempt_id!,R);const x=publicState(await f.store.get(U,A));assert('welcome' in x&&x.welcome===R.welcome);assert(!('worker_id' in x)&&!('user_id' in x));assert.equal(x.status,'done')}finally{await f.close()}});

test('trust events count users before agent creation, deduplicate and reject private payloads',async()=>{const f=await fixture();try{
 await f.db.query('DELETE FROM mtr_harness.agents WHERE user_id=$1',[U]);
 await f.store.touch(U,'security_viewed');await f.store.touch(U,'security_viewed');await f.store.touch(U,'connection_started','google');
 assert.equal((await f.db.query('SELECT * FROM mtr_harness.onboarding_touchpoints')).rows.length,2);
 for(const [event,provider] of [['private message','none'],['security_viewed','arbitrary'],['security_viewed',['google']],['security_viewed',{email:'private'}]])await assert.rejects(()=>f.store.touch(U,event,provider),{status:400});
 const cols=(await f.db.query<{column_name:string}>("SELECT column_name FROM information_schema.columns WHERE table_name='onboarding_touchpoints'")).rows.map(x=>x.column_name).sort();
 assert.deepEqual(cols,['created_at','event','experience','provider','user_id']);
 await f.db.query('DELETE FROM mtr_harness.users WHERE id=$1',[U]);assert.equal((await f.db.query('SELECT * FROM mtr_harness.onboarding_touchpoints')).rows.length,0);
 }finally{await f.close()}});
test('skip connection persists the direct task path across reload, not a WhatsApp gate',async()=>{const f=await fixture();try{await f.store.progress(U,A,'started');await f.store.progress(U,A,'connections_skipped');assert.equal((await createOnboardingStore(f.pool).get(U,A))?.step,'wow')}finally{await f.close()}});
test('feedback requires current viewed result, is owned and idempotent, survives restart without generation',async()=>{const f=await fixture();try{
 const q=await f.store.claim(U,A,'starter'),attempt=q.state.attempt_id!;await f.store.finish(U,A,attempt,{...R,suggestions:[]});
 await assert.rejects(()=>f.store.feedback(U,A,attempt,'useful'),{status:409});await f.store.progress(U,A,'starter_viewed',attempt);
 await assert.rejects(()=>f.store.feedback(V,A,attempt,'useful'),{status:404});await assert.rejects(()=>f.store.feedback(U,A,'old','useful'),{status:409});await assert.rejects(()=>f.store.feedback(U,A,attempt,'arbitrary text'),{status:400});
 await f.store.feedback(U,A,attempt,'useful');await f.store.feedback(U,A,attempt,'useful');await f.store.feedback(U,A,attempt,'needs_work');
 const rows=(await f.db.query<{choice:string}>('SELECT * FROM mtr_harness.onboarding_feedback')).rows;assert.equal(rows.length,1);assert.equal(rows[0].choice,'needs_work');
 const restarted=createOnboardingStore(f.pool);await restarted.init();assert.equal((await restarted.get(U,A))?.feedback_choice,'needs_work');assert.equal((await restarted.claim(U,A,'starter',true)).claimed,false);
 await f.db.query('DELETE FROM mtr_harness.users WHERE id=$1',[U]);assert.equal((await f.db.query('SELECT * FROM mtr_harness.onboarding_feedback')).rows.length,0);
}finally{await f.close()}});
test('selected suggestion and refinement survive restart; cannot select unviewed, foreign or invented suggestion',async()=>{const f=await fixture();try{
 const q=await f.store.claim(U,A,'connected'),attempt=q.state.attempt_id!;await f.store.finish(U,A,attempt,R);
 await assert.rejects(()=>f.store.progress(U,A,'suggestion_selected',attempt,0),{status:409});await f.store.progress(U,A,'wow_viewed',attempt);
 for(const index of [-1,1,0.5,'private text'])await assert.rejects(()=>f.store.progress(U,A,'suggestion_selected',attempt,index),{status:400});
 await f.store.progress(U,A,'suggestion_selected',attempt,0);const restarted=createOnboardingStore(f.pool);let state=publicState(await restarted.get(U,A));assert.equal('selectedSuggestion' in state&&state.selectedSuggestion,0);assert.equal('step' in state&&state.step,'done');
 await restarted.progress(U,A,'refinement_selected',attempt);state=publicState(await f.store.get(U,A));assert.equal('refinementSelected' in state&&state.refinementSelected,true);assert.equal('selectedSuggestion' in state&&state.selectedSuggestion,null);
 await f.store.progress(U,A,'whatsapp_skipped');assert.equal((await f.store.get(U,A))?.step,'done');
 assert.equal((await f.store.claim(U,A,'connected',true)).claimed,false);
}finally{await f.close()}});
