import { spawn } from 'node:child_process';
import { mkdtempSync } from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import { chromium } from 'playwright-core';
import { freePort } from '../dev/local.mjs';
const root = path.resolve('.');
const dataDir = mkdtempSync(path.join(os.tmpdir(), 'brambit-lang-'));
const KEY = 'k';
const ai = http.createServer((req, res) => { res.writeHead(200, { 'content-type': 'application/json' }); res.end(JSON.stringify({ data: [{ id: 'test-model' }] })); });
await new Promise((r) => ai.listen(0, '127.0.0.1', r));
const aiUrl = `http://127.0.0.1:${ai.address().port}/v1`;
const port = await freePort();
const child = spawn(process.execPath, [path.join(root, 'installer', 'brambit.mjs'), '--no-browser'], { env: { ...process.env, BRAMBIT_DATA_DIR: dataDir, BRAMBIT_PORT: String(port), NO_PROXY: '127.0.0.1,localhost', no_proxy: '127.0.0.1,localhost' }, stdio: ['ignore', 'pipe', 'inherit'] });
let out = '';
const url = await new Promise((resolve) => child.stdout.on('data', (b) => { out += b; process.stdout.write(b); const m = out.match(/(http:\S+#code=\S+)/); if (m) resolve(m[1]); }));
const browser = await chromium.launch({ executablePath: process.env.BROWSER_PATH || '/usr/bin/chromium', args: ['--no-sandbox', '--no-proxy-server', '--lang=pt-BR'] });
const ctx = await browser.newContext({ locale: 'pt-BR' });
const page = await ctx.newPage();
page.on('request', (r) => { if (r.url().includes('/api/')) console.log('[req]', r.method(), r.url().replace(/^http:\/\/[^/]+/, ''), r.headers()['accept-language'] || '-'); });
await page.goto(url);
console.log('navigator.languages =', await page.evaluate(() => navigator.languages));
console.log('setup h1 =', await page.textContent('h1')); console.log('accept-language sent =', await page.evaluate(async () => navigator.language));
await page.screenshot({ path: 'tmpcheck/1-setup.png', fullPage: true });
await page.fill('#name', 'Marcos Teste'); await page.fill('#email', 'm@example.com');
await page.fill('#password', 'a-long-enough-password-1'); await page.fill('#password2', 'a-long-enough-password-1');
await page.check('input[name=provider][value=other]');
await page.fill('#url', aiUrl); await page.fill('#model', 'test-model'); await page.fill('#key', KEY);
await page.click('#submit');
await page.waitForURL((u) => !String(u).includes('#'), { timeout: 240000 }).catch(() => {});
await page.waitForTimeout(8000);
console.log('app url =', page.url(), 'html lang =', await page.evaluate(() => document.documentElement.lang));
console.log('wizHi =', await page.textContent('#wizHi').catch(() => '?'));
console.log('cookies =', (await ctx.cookies()).map((c) => c.name + '=' + c.value.slice(0, 12)));
console.log('me.locale =', await page.evaluate(async () => (await (await fetch('/api/me')).json()).locale));
await page.screenshot({ path: 'tmpcheck/2-app.png', fullPage: false });
await browser.close(); if (process.platform === 'win32') { try { (await import('node:child_process')).execFileSync('taskkill', ['/T', '/F', '/PID', String(child.pid)], { stdio: 'ignore' }); } catch {} } else child.kill('SIGTERM'); ai.close();
process.exit(0);
