// The AI providers the setup page offers, how to test a key before saving it,
// and the modelos.yaml written from the choice. Model ids are the ones the
// core already prices (web/pricing.mjs); "other" is any service speaking the
// OpenAI protocol (OpenRouter, Ollama, vLLM...), with the model typed by hand.
import { stringify } from 'yaml';

export const PROVIDERS = {
  together: { url: 'https://api.together.xyz/v1', model: 'deepseek-ai/DeepSeek-V4.1-Flash', keyVar: 'TOGETHER_API_KEY' },
  openai: { url: 'https://api.openai.com/v1', model: 'gpt-5.4-mini', keyVar: 'OPENAI_API_KEY' },
  gemini: { type: 'gemini', url: 'https://generativelanguage.googleapis.com/v1beta', model: 'gemini-3.7-flash', keyVar: 'GEMINI_API_KEY' },
  other: { url: null, model: null, keyVar: 'OTHER_API_KEY' },
};

// What the person chose → {provider, url, model, key} or {error}.
export function choice({ provider, url, model, key }) {
  const p = PROVIDERS[provider];
  if (!p) return { error: 'invalid_provider' };
  const k = String(key || '').trim();
  if (provider !== 'other') return k ? { provider, url: p.url, model: p.model, key: k } : { error: 'missing_key' };
  let u;
  try { u = new URL(String(url || '').trim()); } catch { return { error: 'invalid_url' }; }
  if (!/^https?:$/.test(u.protocol) || u.username || u.password) return { error: 'invalid_url' };
  const m = String(model || '').trim();
  if (!m) return { error: 'missing_model' };
  return { provider, url: u.href.replace(/\/+$/, ''), model: m, key: k };
}

// Lists the provider's models with the key: proves the key works and that the
// model exists, without spending anything. → {ok:true} or {ok:false, error}.
export async function testKey({ provider, url, model, key }, fetchImpl = fetch) {
  const gemini = PROVIDERS[provider]?.type === 'gemini';
  const headers = gemini ? { 'x-goog-api-key': key } : (key ? { authorization: `Bearer ${key}` } : {});
  let res;
  try { res = await fetchImpl(`${url}/models${gemini ? '?pageSize=1000' : ''}`, { headers, signal: AbortSignal.timeout(15000) }); }
  catch { return { ok: false, error: 'no_connection' }; }
  if (res.status === 401 || res.status === 403) return { ok: false, error: 'key_rejected' };
  if (!res.ok) return { ok: false, error: 'provider_error', status: res.status };
  const body = await res.json().catch(() => null);
  const list = gemini ? body?.models : (Array.isArray(body) ? body : body?.data);
  if (!Array.isArray(list)) return { ok: false, error: 'provider_error', status: res.status };
  const ids = new Set(list.map((m) => String(gemini ? m?.name : m?.id).replace(/^models\//, '')));
  return ids.has(model) ? { ok: true } : { ok: false, error: 'model_missing' };
}

// modelos.yaml with a single provider doing every function. The key is NOT in
// it: only the name of the environment variable the launcher fills in. The keys
// of the file itself (provedores, funcoes, padrao...) are the core's format.
export function modelsYaml({ provider, url, model, key }) {
  const p = PROVIDERS[provider];
  const prov = p.type === 'gemini' ? { tipo: 'gemini', chave: p.keyVar } : { endereco: url, ...(key ? { chave: p.keyVar } : {}) };
  return `# Generated by the Brambit installer. To change it, run the setup again.\n${stringify({ provedores: { [provider]: prov }, funcoes: { padrao: { modelo: `${provider}/${model}` } } })}`;
}
